### ISSUE TITLE
[Bug] Portals only work one-way

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/Blender-WMO-import-export-scripts#1]
Portals only work in one direction. Other direction is not rendered.

**Comment by skarnproject** [comment]
Known issue. Should be gone by itself when I change the way portal relations are created.

**Comment by gratural** [comment]
Portals are working properly. But if you add new ones, when exported, they are switched their settings. So portal A  connects GroupID's  0 and 1 is working correctly. If you add Portal B with setting GroupID 1 and 2, at the entrance to the game, they both will work wrong. If do import WMO to Blender, it will be seen that portal A now connects 1 and 2 ID's, and portal B - 0 and 1. It bug is constantly repeated with the addition of portals: they switch your settings from first to last.

**Comment by Kallar12** [comment]
I only have one portal and only 2 groups and those 2 groups should be connected. The portal works ingame when you pass through it but one side is not rendered. @gratural 

https://gyazo.com/75eff5717cd0161559b8a93cefa34edb
https://gyazo.com/a8c4a0007e874339874c919c5ae385d2
