### ISSUE TITLE
Portals are broken

### ISSUE THREAD

**Issue by gratural** [WowDevTools/Blender-WMO-import-export-scripts#12]
On exporting, portals take this shape:
http://prntscr.com/efs1uv
Same shape as, if you make portal from standart plane.
Obviously, such a portal is working wrongly: at least one side of him are non trasparrent.

**Comment by skarnproject** [comment]
I am aware of the issue. I am currently working on the solution to automatically set up vertex order and direction. This is still a valid plane though, the shape changes nothing. So, to make it work for now, play with direction or plane normal.

**Comment by gratural** [comment]
Now works fine. Playing with twisted portals are no chances to success - because half surface of portal don't works. With both sides.

**Comment by skarnproject** [comment]
So is the issue with crippled geometry fixed with one of my recent commits? Sorry, don't quite get what you mean.

**Comment by gratural** [comment]
Exactly). Portals have been damaged about 3 days ago, i  missed commit which are guilty . Just export any wmo with yesterday's repo and then import him back into the blender.
