### ISSUE TITLE
Vertex shading indoors

### ISSUE THREAD

**Issue by Amaroth** [WowDevTools/Blender-WMO-import-export-scripts#13]
In indoor group has vertex shading off, client will crash. If vertex shading is on, but none is set to actual geometry, client will crash.

I'd suggest turning vertex shading on and assigning some default color value to all verticles for all indoor groups on export, if they have vertex shading turned off or if they don't have vertex shading assigned to all verticles, so one doesn't have to do this by hand.

**Comment by gratural** [comment]
As variant, you can use bpy.ops.paint.vertex_color_set() or even bpy.ops.paint.vertex_color_dirt() when 'indoor' flag has been selected. But only once, and if vertex colors are not set.

**Comment by skarnproject** [comment]
Should be solved. Please test and confirm.

**Comment by Amaroth** [comment]
It seems everything works fine now.
