### ISSUE TITLE
Portal plane creation

### ISSUE THREAD

**Issue by Amaroth** [WowDevTools/Blender-WMO-import-export-scripts#14]
When turning object to WMO portal, there is no possibility to set WMO groups which should be connected by portals. One needs to access every single portal, one by one, and set this by hand in object properties. This makes mass creation of multiple portals quite slow and annoying.

The another thing is that when picking WMO groups portal is to be connected to, there are another portals and different kinds of objects to pick from. There should be only WMO groups in drop down menu.

The last thing is that there is no default WMO group set when object is turned to portal plane. So right now, even when I've got only one indoor and one outdoor group, I've got to set them there anyway.

**Comment by Supora** [comment]
> The last thing is that there is no default WMO group set when object is turned to portal plane. So right now, even when I've got only one indoor and one outdoor group, I've got to set them there anyway.
I don't have such thing. If I have only one group I can just export it without any portal plane.

**Comment by Amaroth** [comment]
Noone said that there is any need of having portal. There is none. Read it once again :P.
