### ISSUE TITLE
[Proposal] Add humanscale creator

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#15]
Task:
Make the **[Add HumanScale]** button which will generate humanscale-model. That will be very helpful for fast-checking your model proportions. 

Proposal for performance:
You can make only 3d-box which will have the same size with humanscale (x-y-z dimensions)

![0205f0b](https://cloud.githubusercontent.com/assets/25208446/23582503/6b1a43c8-014d-11e7-918e-9c0fdfa27188.gif)

**Comment by gratural** [comment]
Very useful thing!
Of course, it should not be  exported, also not visible in list of portals, fogs and other.

**Comment by skarnproject** [comment]
Done.
