### ISSUE TITLE
Liquid's surface has wrong coords

### ISSUE THREAD

**Issue by gratural** [WowDevTools/Blender-WMO-import-export-scripts#16]
In Blender:
http://prnt.sc/eg8256
In Noggit:
http://prnt.sc/eg822d

On export, all luquid suface mesh in scene, always take wrong position - one of her corners placed on 0.0.0 coordinate.

**Comment by skarnproject** [comment]
Should be fixed

**Comment by gratural** [comment]
Works fine!
I want to order a couple of improvements.
- Setting one liquid surface for several indoor groups. (Example implemented as creating several liquids on export, filled by wmo group selection box)
Support for complex surfaces. (Because, a liquid surface in first indoor group,  sometimes, emerges through the outdoor group mesh, and be  visible from world)
