### ISSUE TITLE
[Bug] Hidden faces broking mesh

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#17]
**Actions To Reproduce:**

![2017-03-06_22-31-50](https://cloud.githubusercontent.com/assets/25208446/23622124/410255e4-02bf-11e7-9cf8-43fdc9afca26.gif)

**Excepted Result:** broken tris-faces on mesh.

**Comment by skarnproject** [comment]
Fixed.
