### ISSUE TITLE
[Bug] Picker crash in Edit mode

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#18]
**Steps to reproduce:**
1. Use **Add Water** 
2. Enable **Edit Mode**
3. Click on **Picker** icon

![2017-03-06_23-33-35](https://cloud.githubusercontent.com/assets/25208446/23623908/9e2371ee-02c5-11e7-8d49-a6c6de4a39e7.gif)

**Excepted result:** console crash

**Comment by skarnproject** [comment]
Fixed.
