### ISSUE TITLE
[Bug] Exporting casues Wmo to be filled with Water

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/Blender-WMO-import-export-scripts#2]
c029ecac2b7bd3204fe21c2fec0f6530e80c2e04 

Since this commit when I regulary export a WMO it is filled with Water

https://gyazo.com/6bab17b86be0ec40bc2cd2344d51ded9
https://gyazo.com/4b7a33904544027417926e34997980f0

**Comment by skarnproject** [comment]
Should be fixed in https://github.com/WowDevTools/Blender-WMO-import-export-scripts/commit/3c2ef0ee6651907bdbf414c30947a0cd06d96563

**Comment by Kallar12** [comment]
Still there

**Comment by gratural** [comment]
@Kallar12, try set on flag "Fill water", when exporting your WMO.
@Skarn, as i think, there is a reason set this flag is turned on by default

**Comment by skarnproject** [comment]
Please test as of https://github.com/WowDevTools/Blender-WMO-import-export-scripts/commit/777894e5f62065b89dd60695724ef4bc0b934bfd commit.

**Comment by Kallar12** [comment]
Fixed with 777894e5f62065b89dd60695724ef4bc0b934bfd

**Comment by Kallar12** [comment]
Was fixed is now back in!

**Comment by Kallar12** [comment]
Solved in d0cac4bb2b8e36769c909e131d6167c381ac91b4
