### ISSUE TITLE
[Bug] Texture path doesn't work correctly

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#25]
**Steps to reproduce:**
1. Create mesh
2. Apply the texture with uv
3. Type your texture relative path in scene properties:
![image](https://cloud.githubusercontent.com/assets/25208446/23903730/56cceaf0-08e7-11e7-9a9e-328882a36931.png)
4. Click on **Texface to Material** button
5. Click on **Fill textures** button

**Excepted result:**
![image](https://cloud.githubusercontent.com/assets/25208446/23903839/b3bf7bd8-08e7-11e7-8fde-1ef80e34e865.png)
 Your texture will have only own name without full texture path.

**Comment by skarnproject** [comment]
What is the real path to PNG file of this texture?

**Comment by BalkronPainter** [comment]
D:\Work\WoWDevKit\World of Warcraft\Data\patch-7.MPQ\DUNGEONS\TEXTURES\6or_garrison\6or_garrison_workshop_floor.blp
