### ISSUE TITLE
Mesh's Group ID's

### ISSUE THREAD

**Issue by gratural** [WowDevTools/Blender-WMO-import-export-scripts#3]
When exporting to WMO, groups are getting unpredictable and uncomfortable ID. They takes ID's in order when they are added to scene (can make sure, by reimport WMO, turning off "Alphabetically" in Outliner and verify ID's names and his order in list) It is particularly important, that the ID's will change each time, after addition new meshes. Maybe you should change order list on export WMO's groups, from last to first, or he can be alphabetical.

**Comment by skarnproject** [comment]
Does not sound possible right now. I am just iterating through Blender's context. I will rework all order-related features in order to be group ID-independent. So, it won't matter anymore.

**Comment by gratural** [comment]
Got it by using parent-child relation. This also fixes twisted portal settings. This is my short indian script.  May be it useful for you.
[hierarchy_ordering.py.txt](https://github.com/WowDevTools/Blender-WMO-import-export-scripts/files/800791/hierarchy_ordering.py.txt)

**Comment by gratural** [comment]
Issue are not actual after rewriting portal export function.
