### ISSUE TITLE
[Bug] In-Game crash without crash at export

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#6]
Steps To Reproduce:
1) Enable **Vertex Color** in any group
![image](https://cloud.githubusercontent.com/assets/25208446/23367026/9ae27034-fd2a-11e6-83fe-d454b976755b.png)

2) Your mesh must be with no vertex color in **Vertex Paint** window

3) Export WMO

Expected result: Crash when your world loads (with no crash-window)

**Comment by skarnproject** [comment]
Should be fixed as of https://github.com/WowDevTools/Blender-WMO-import-export-scripts/commit/7b8dd248e313224360863ad268ef69089f50d9cd

**Comment by BalkronPainter** [comment]
Problem doesn't disappear. There are the same result.

**Comment by BalkronPainter** [comment]
Fixed
