### ISSUE TITLE
[Request] Remove vertex data spam

### ISSUE THREAD

**Issue by BalkronPainter** [WowDevTools/Blender-WMO-import-export-scripts#7]
Steps To Reproduce:

1. Select any group
2. Click on **Quick Collision** button several times

![q8g3qsr](https://cloud.githubusercontent.com/assets/25208446/23368547/074b8cf6-fd30-11e6-84d6-995cbc612ab8.gif)

Expected result: 
Your group will have lots of vertex data groups

There are no bug but it causes few problems with vertex-data-work (Vertex Color/LightMap assignment)

Task: 
Make the **Quick Collision** function as a replacer of vertex data (only one vertex data group)

**Comment by skarnproject** [comment]
Should be fixed as of https://github.com/WowDevTools/Blender-WMO-import-export-scripts/compare/16c8bf41d0d8...c485d661e44d. Please, test and confirm.
